### ISSUE TITLE
undefined method `setup' for a test file in test/workers

### ISSUE THREAD

**Issue by jtmkrueger** [blowmage/minitest-rails#204]
It seems like I'm not getting anything to load into the test. `setup` works fine for me in my controller and model specs, but it's not available in this worker folder I created.

Here's the test:
```
require "test_helper"

describe NotifiyAgentOfNewLeadEmailWorker do
  setup do
    stub_request(:post, "https://mandrillapp.com/api/1.0/messages/send-template.json")
  end

  Sidekiq::Testing.inline! do
    describe 'perform' do
      parameters = FactoryGirl.build(:notification).attributes.symbolize_keys
      NotifiyAgentOfNewLeadEmailWorker.perform_async(parameters)
    end
  end
end
```

Here's the error I get:
```
▶ rails test
Running via Spring preloader in process 6434
/home/jk/code/notifications/test/workers/notify_agent_of_new_lead_email_worker_test.rb:4:in `block in <top (required)>': undefined method `setup' for #<Class:0x0056156f548230> (NoMethodError)
        from /home/jk/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/minitest-5.10.2/lib/minitest/spec.rb:83:in `class_eval'
        from /home/jk/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/minitest-5.10.2/lib/minitest/spec.rb:83:in `describe'
        from /home/jk/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/minispec-metadata-2.0.0/lib/minispec-metadata/describe_with_metadata.rb:24:in `describe'
        from /home/jk/code/notifications/test/workers/notify_agent_of_new_lead_email_worker_test.rb:3:in `<top (required)>'
        from /home/jk/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `require'
        from /home/jk/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `block in require'
        from /home/jk/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:258:in `load_dependency'
        from /home/jk/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `require'
        from /home/jk/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/test_unit/test_requirer.rb:14:in `block in require_files'
        from /home/jk/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/test_unit/test_requirer.rb:13:in `each'
        from /home/jk/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/test_unit/test_requirer.rb:13:in `require_files'
        from /home/jk/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/test_unit/minitest_plugin.rb:94:in `plugin_rails_init'
        from /home/jk/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/minitest-5.10.2/lib/minitest.rb:81:in `block in init_plugins'
        from /home/jk/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/minitest-5.10.2/lib/minitest.rb:79:in `each'
        from /home/jk/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/minitest-5.10.2/lib/minitest.rb:79:in `init_plugins'
        from /home/jk/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/minitest-5.10.2/lib/minitest.rb:130:in `run'
        from /home/jk/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/test_unit/minitest_plugin.rb:77:in `run'
        from /home/jk/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/minitest-5.10.2/lib/minitest.rb:63:in `block in autorun'
        from /home/jk/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/jk/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from -e:1:in `<main>'
```

Is there a step I'm missing to have access to `setup` in this file or other test files in this directory?

**Comment by zenspider** [comment]
It's called `before` in minitest/spec:

http://docs.seattlerb.org/minitest/Minitest/Spec/DSL.html#method-i-before

If there is a block form of `setup` available in rails, then there's something wrong with the rails bootstrap (usually via the test_helper.rb file).

**Comment by blowmage** [comment]
Likely your other tests are getting their test classes properly identified, using ActiveSupport::TestCase and ActionDispatch::IntegrationTest, where the `setup` method exists. But your test is using Minitest::Spec which does not have a `setup` method.

**Comment by jtmkrueger** [comment]
I'm able to use `setup` in all my tests that are in standard directories (controllers, models) and now discovered that `before` is available in the nonstandard directories (workers, services, etc.). Does that sound like how things should be working?

Thank you to both of you for responding to my question. I'm coming from writing rspec tests primarily and really enjoying the transition to minitest.

**Comment by jtmkrueger** [comment]
This is what my `test_helper.rb` looks like:
```
ENV['RAILS_ENV'] = 'test'
require File.expand_path('../../config/environment', __FILE__)
require 'rails/test_help'
require 'sidekiq/testing'
require 'minitest/rails'
require 'webmock/minitest'

# Uncomment for awesome colorful output
require 'minitest/pride'

class ActiveSupport::TestCase
  include FactoryGirl::Syntax::Methods
  fixtures :all
  Sidekiq::Testing.inline!

  # Add more helper methods to be used by all tests here...
end
```
Seems pretty simple, but perhaps there's some configuration code I need to have to include those non-standard folders?

**Comment by blowmage** [comment]
If you want to force your test to use `ActiveSupport::TestCase` (which has `setup` defined as well as runs within a database transaction) instead of `Minitest::Spec`, you can do that by adding `:model` to your additional spec description:

```ruby
describe NotifiyAgentOfNewLeadEmailWorker, :model do
```

**Comment by jtmkrueger** [comment]
That worked great @blowmage thanks!
